CREATE TABLE Especialidad(
ID_Especialidad int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Nombre varchar (30) not null
);

CREATE TABLE Medico (
cedula int primary key not null,
especialidad int not null,
num_colegiado int not null,
nombre varchar(30) not null,
primer_apellido varchar(30) not null,
segundo_apellido varchar(30) not null,
correo varchar(100) not null,
telefono varchar(8) not null,
provincia varchar(50) not null,
canton varchar(50) not null,
distrito varchar(50) not null,
otros varchar(1000) not null,
edad int not null,
genero number(1) not null,
FOREIGN KEY (especialidad) References Especialidad(Id_Especialidad)
);


CREATE TABLE Paciente(
cedula int primary key not null,
nombre varchar (30) not null,
primer_apellido varchar(30) not null,
segundo_apellido varchar(30) not null,
telefono varchar (8) not null,
correo varchar(100) not null,
provincia varchar(50) not null,
canton varchar(50) not null,
distrito varchar(50) not null,
otros varchar(1000) not null,
edad int not null,
genero number (1) not null
);

CREATE TABLE Tratamiento(
ID_Tratamiento int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY not null,
nombre varchar (30) not null,
duracion varchar (100) not null,
costo decimal (10,2) not null 
);

CREATE TABLE Medicamento(
codigo_medicamento int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
nombre varchar(30) not null,
descripcion varchar(1000) not null,
indicaciones varchar(200) not null,
efectos_secundarios varchar(200) not null,
fecha_caducidad varchar(20) not null,
costo decimal(10,2) not null,
dosis varchar (1000) not null
); 

CREATE TABLE Tratamiento_Medicamento(
ID_Tratamiento int not null,
ID_Medicamento int not null,
FOREIGN KEY (ID_Tratamiento) REFERENCES Tratamiento(ID_Tratamiento),
FOREIGN KEY (ID_Medicamento) REFERENCES Medicamento(codigo_medicamento)
);

CREATE TABLE Tipo_Cita(
ID_tipo_cita int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Nombre varchar(30) not null,
Descripcion varchar(30) not null
);

CREATE TABLE Cita(
ID_Cita int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Cedula_Medico int not null,
Cedula_Paciente int not null,
ID_Tipo_cita int not null,
Fecha date not null,
Motivo_Cita varchar(200) not null,
Estado varchar (100) not null,
FOREIGN KEY (Cedula_Medico) REFERENCES Medico(cedula),
FOREIGN KEY (Cedula_Paciente) REFERENCES Paciente(cedula),
FOREIGN KEY (ID_Tipo_cita) REFERENCES Tipo_Cita(ID_tipo_cita)
);


CREATE TABLE Pago(
ID_Pago int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
ID_Paciente int not null,
Monto decimal(10,2) not null,
fecha date not null,
Metodo_Pago varchar (30) not null,
Estado_Pago varchar (30) not null,
Detalle varchar (30) not null,
FOREIGN KEY (ID_Paciente) REFERENCES Paciente(cedula)
);

CREATE TABLE Facturas(
ID_Factura int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
ID_Pago int not null,
FOREIGN KEY (ID_Pago) REFERENCES Pago (ID_Pago)
);

CREATE TABLE Historial_Medico(
ID_Historial int GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY not null,
Cedula_Paciente int not null,
FOREIGN KEY (Cedula_Paciente) REFERENCES Paciente(cedula)
);

CREATE TABLE Historial_Tratamiento(
ID_Tratamiento int not null,
ID_Historial int not null,
FOREIGN KEY (ID_Tratamiento) REFERENCES Tratamiento(ID_Tratamiento),
FOREIGN KEY (ID_Historial) REFERENCES Historial_Medico (ID_Historial)
);


CREATE TABLE Cita_Historial(
ID_Cita int not null,
ID_Historial int not null,
FOREIGN KEY (ID_Cita) REFERENCES Cita(ID_Cita),
FOREIGN KEY (ID_Historial) REFERENCES Historial_Medico (ID_Historial)
);







